version: "3.2"

services:
  db:
    network_mode: host
    image: postgres
    container_name: "postgres-ka"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=soundbit_dev
    ports:
      - 5432:5432

  redis:
    network_mode: host
    container_name: redis
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
